#Application Configuration
server:
  port: 8093

# To See H2 Console in Browser:
# http://localhost:8093/h2-console
# Enabling H2 Console
spring:
  application:
    name: shopping-services
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost/shopingDB?serverTimezone=America/Mexico_City #&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: sasa

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


